name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Upgrade to v3 for checkout
      - name: Use Node.js
        uses: actions/setup-node@v3 # Upgrade to v3 for setup-node
        with:
          node-version: "20" # Check documentation for correct syntax
      - run: npm install
      - run: npm test
