name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Atualizado para v4
      - name: Use Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: "16" # Especifique a versão desejada do Node.js, por exemplo, "16"
      - run: npm install
      - run: npm test
